version: 9.1.0.{build}-{branch}
os: MinGW

image: Visual Studio 2019

platform:
  - x64

build:
  parallel: true
  verbosity: detailed

configuration:
  - release
#  - debug

environment:
  global:
    NJOBS: 4
  matrix:
    - PLATFORM: x64
      MSYSTEM: MINGW64
      COMPILER: gcc
    - PLATFORM: x64
      MSYSTEM: MINGW64
      COMPILER: clang
    - PLATFORM: x86
      MSYSTEM: MINGW32
      COMPILER: gcc
    - PLATFORM: x86
      MSYSTEM: MINGW32
      COMPILER: clang

install:
  - ports\ci\appveyor\environment_setup.bat
  - C:\msys64\usr\bin\bash -lc "cd /c/projects/webcamoid && ./ports/ci/appveyor/install_deps.sh"

build_script:
  - ports\ci\appveyor\environment_setup.bat
  - C:\msys64\usr\bin\bash -lc "cd /c/projects/webcamoid && ./ports/ci/appveyor/build.sh"

after_build:
  - ports\ci\appveyor\environment_setup.bat
  - C:\msys64\usr\bin\bash -lc "cd /c/projects/webcamoid && ./ports/ci/appveyor/deploy.sh"

notifications:
  - provider: Email
    to:
      - hipersayan.x@gmail.com
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true
